// Code generated by generate.go. DO NOT EDIT.

package roots

const (
	expectedCountCACertsIncludedAll            = 181
	expectedCountCACertsIncludedWebsites       = 144
	expectedCountCACertsIncludedEmail          = 105
	expectedCountCACertsIncludedHashesAll      = 181
	expectedCountCACertsIncludedHashesWebsites = 144
	expectedCountCACertsIncludedHashesEmail    = 105
	expectedCountCACertsRemoved                = 86
	expectedCountCACertsRemovedHashes          = 86
	expectedCountCACertsUpcomingRemovals       = 0
	expectedCountCACertsUpcomingRemovalsHashes = 0
)
