// Code generated by generate.go. DO NOT EDIT.

package roots

const (
	expectedCountCACertsIncludedAll            = 175
	expectedCountCACertsIncludedWebsites       = 143
	expectedCountCACertsIncludedEmail          = 101
	expectedCountCACertsIncludedHashesAll      = 175
	expectedCountCACertsIncludedHashesWebsites = 143
	expectedCountCACertsIncludedHashesEmail    = 101
	expectedCountCACertsRemoved                = 87
	expectedCountCACertsRemovedHashes          = 87
	expectedCountCACertsUpcomingRemovals       = 1
	expectedCountCACertsUpcomingRemovalsHashes = 1
)
