// Code generated by generate.go. DO NOT EDIT.

package roots

const (
	expectedCountCACertsIncludedAll            = 167
	expectedCountCACertsIncludedWebsites       = 120
	expectedCountCACertsIncludedEmail          = 90
	expectedCountCACertsIncludedHashesAll      = 167
	expectedCountCACertsIncludedHashesWebsites = 120
	expectedCountCACertsIncludedHashesEmail    = 90
	expectedCountCACertsRemoved                = 100
	expectedCountCACertsRemovedHashes          = 100
	expectedCountCACertsUpcomingRemovals       = 1
	expectedCountCACertsUpcomingRemovalsHashes = 1
)
